application: cxmytest
version: 2
runtime: python27
api_version: 1
threadsafe: no
  
handlers:
- url: /twitter/.*
  script: twitter.py
- url: /weibo/.*
  script: testweibo.py
- url: /fetch/.*
  script: fetchurl.py
- url: /.*
  script: helloworld.py