application: cxmytest
version: 1
runtime: python27
api_version: 1
threadsafe: no

handlers:
- url: /tr/.*
  script: twitter.py
- url: /weibo/.*
  script: weibo.py
- url: /conn/.*
  script: TwitterDumpToWeibo.py
- url: /fetch/.*
  script: fetchurl.py
- url: /main/.*
  script: main.py